# Nombre de la aplicación y el puerto de la pestaña web
spring.application.name=netflix
server.port=8080

# CONFIGURACIÓN PARA MONGODB
# Conexión local por defecto (el puerto de Mongo es el 27017)
# 'netflix_db' es el nombre de la base de datos que se creará automáticamente en Mongo
spring.mongodb.uri=mongodb://localhost:27017/netflix_db